### PR TITLE
add support for asymmetric crypto based jwt signatures

### PR DESCRIPTION
**Pull request by macabrus**
# Checklist
Please put a X in the boxes as evidence of reading through the checklist.

- [x] I have forked the project, and raised this PR on a feature branch. 
- [x] `make githooks` has been run, and my git commit message was accepted by the git hook.
- [x] `make daemon-compile` runs without any issues.
- [x] `make daemon-codestyle` runs without any issues.
- [x] `make daemon-unittests` runs without any issues.
- [x] `make webui-codestyle` runs without any issues. 
- [x] I understand and accept the [AGPL-3.0 license](LICENSE) and [code of conduct](CODE_OF_CONDUCT.md), and my contributions fall under these. 

Note: excuse my Golang profficiency 😸

### CODE REVIEW

**Comment by macabrus** [comment]
actually wait, don't merge yet, I'm gonna add tests to cover valid/invalid jwt signatures

**Comment by jamesread** [comment]
@macabrus , first of all, thanks for the work on this. At a glance the code looks fine, but I'll do a more detailed review prior to merging.

What I really need is some basic instructions for how to setup a test environment for this, as well. Eg, how to generate some example certs with a proxy config that uses them - this will allow OliveTin to have more robust integrated tests, and make it easier for the code to be maintained (as I'm not all that familiar with this, yet!). 

Could you also update your feature branch to maintain - pull or rebase or whatever - at the moment the changes cannot be easily automatically merged.

**Comment by macabrus** [comment]
@jamesread yes, this is exactly what I am writing tests for. Will be pushing stuff here soon so you'll be able to check it out.

okay, will work on main branch.

**Comment by macabrus** [comment]
@jamesread could you please peek into unit test? I am essentially did key generation and jwt signing part but I am having some problem in dummy rest handler simulating cookie parsing.

**Comment by jamesread** [comment]
Thanks so much for taking the time, and sorry for the long delay on reviewing changes.

I'm literally spending 2 days dedicated to OliveTin updates right now, and I don't want this to get left behind. I'm going to update the branch and merge what you've got, close this issue and then create additional individual issues for anything that might pop up later.

Thank you SO MUCH for taking the time to contribute to OliveTin, and again I'm so sorry life just got in the way of me reviewing this, leaving you waiting longer than you should have. I hope you look to contribute to OliveTin again in the future!

**Pull request merged**
